---
title: "The Temporal Network of Hospital Patient Transfers Paper"
authors:
    - name: David Wu
    - name: Michael Lydeamore
    - name: Andrew Stewardson
    - name: Tjibbe Donker
    - name: Nic Geard
    - name: OTHER AUTHORS
date: today
format:
    html: default
    pdf: default
---

# Introduction

Antimicrobial resistance is bad. In Victoria, Australia, we have observed CPE, and want to understand how the underlying movement of patients could affect the spread of CPE and other related AMR in the future.
The focus of this paper is on the patient movement network: ways of representing, simplifying, and approximating those patient movements; and how those representations of patient movement affect the spread of a hypothetical infection between hospitals in the Victorian healthcare system.

# Methods

## Generating the temporal network
We have line-listed patient movement data between {start_date} and {end_date}. This allows us to generate exact patient movement networks up to minute precision.
By arranging patient journeys within this dataset, we can construct a network of patient transfers when two consecutive (but not necessarily temporally adjacent) admissions of the same patient occur at different healthcare facilities.
These then define a temporal network where a (single) patient being discharged from hospital $A$ at time $t_1$ and admitted to hospital $B$ at a later time $t_2$, where there are no other event in between, contributes to a weight of 1 on the edge $(A, t_1) \to (B, t_2)$.
To simplify the computational expense of such a network, and to protect patient anonymity, we choose to discretise events in the system. This is done by choosing some window size $W$, and treating events that occur between $t$ and $t+W$ as all occuring at $t$. This causes some transfers to "disappear" depending on the choice of $W$.
The patient transfers can be "indirect", where the patient is not present in the hospital system for some amount of time between consecutive admissions, i.e. when $t_2 \neq t_1$. From inspecting the dataset, we see that there is a significant number of transfers that are indirect, and the time between consecutive admissions is distributed sub-exponentially, witha  heavy tail.
These types of transfers imply causal edges between hospitals that are neither synchronous (occur at the same time), nor persistent (where the effect of a cause at time $t_1$ is not felt over some interval $(t_1, t_2)$), which make it challenging to fit a temporal network generated by this dataset into classical temporal network frameworks of representation.

## Projecting the temporal network
We can project these causal edges by making their effects persistent in a hospital. 
So an edge $(A, t_1) \to (B, t_2)$ can be decomposed into:

1. $(A, t_1) \to (B, t_1)$ and $(B, t_1) \to \dots \to (B, t_2)$
2. $(A, t_1) \to \dots \to (A, t_2)$ and $(A, t_2) \to (B, t_2)$

This causes an implied increased infection pressure at certain hospital nodes. This sort of projection also loses specificity of temporal causality. By inspecting the temporal network that results from this projection, you cannot tell if a patient is moving from $t_1$ to $t_2$ or to $t_3$. 

There is also a mechanistically distinct projection, where we introduce "home" nodes for each facility. For some facility $A$, the home node is denoted $A'$.
Thus we could also project the edge as 

- $(A, t_1) \to (A', t_1)$ and $(A', t_1) \to \dots \to (A', t_2)$ and $(A', t_2) \to (B, t_2)$.

This is an ideal projection, but is difficult to achieve. Specifically, it is difficult to control the duration that an individual spends in the home node.
However, this projection still loses temporal causal specificty, as above.

## Simulating on Networks

We use a discrete time Markov chain model to simulate the spread of infection. Simulations step forward in timesteps of $\delta t$, and events within the window $\delta t$ are assumed to be independent.
For simplicity, we model the infection as SI or SIS, depending on the choice of removal rate; we assume that all facilities are at capacity all the time, which allows us to remove the explciit tracking of susceptibles.
When individuals are removed, they are randomly chosen to either never return or eventually return (to the hospital system); if they do, they are randomly placed into a transfer bucket which has two properties:

- where they will readmit
- when they will readmit

For a "full" temporal simulation, both where and when are specified; for a "reduced" simulation, only "where" is specified, and "when" falls into one of two buckets: immediately, or not immediately.
We use a "full" temporal simulation with the unprojected temporal network, and a "reduced" simulation for any projection of that temporal network that has lost temporal information.

<Specification of the model here>

| Parameter | Description |
|-----------|---------------------------------------|
| $\beta$   | Rate of infection per unit infected per day |
| $\eta$    | Rate of removal/recovery |
| $\gamma$  | Rate of discharge from hospital |
| $M$       | Transition matrix inferred from network |

# Results

We run a range of experiments.

## Leading results


## Linelist simulations

We can also run this model structure on top of the actual line list, instead of aggregating patient movement into a network.

## No infection simulations 

To isolate the effect of the projections on the movement of patients, we can simulate the model with parmeters $\beta = 0, \eta=0$.

## Home node projection simulations


## Markovian Approximation of movement