
<!-- Notations

- $u,v$ for locations; discrete, usually subscript
- $s,t$ for times; continuous, usually function inputs/variables
- $T, \omega, \Omega$ for characteristic times
- $N$ as a size variable
- $x, y, z$ are state variables; often functions of location and time -->

:::{.hidden}
$$
\newcommand{\dd}[2][t]{\frac{\mathrm{d}#2}{\mathrm{d}#1}}
\newcommand{\ceil}[1]{\lceil#1\rceil}
$$
:::

:::{#fig-general-diagram}
```{.tikz}
%%| format: svg
%%| filename: movement_general_case
%%| img-width: 800
%%| fig-cap: general movement processes
\usetikzlibrary{arrows.meta, positioning, shapes.geometric, shapes.arrows}

\begin{tikzpicture}[
  node distance=2cm and 4cm,
  >=latex
]
  \tikzset{
    squarx/.style= {
      regular polygon,
      regular polygon sides=4
    }
  }
  \tikzset{
    house/.style= {
      single arrow,
      shape border rotate=90,
      single arrow head extend=0pt,
      single arrow tip angle=120,
      minimum height=0.75cm,
      minimum width=0.75cm
    }
  }

  \node[draw, squarx] (A) {$u$};
  \node (X) [right=of A] {};
  \node[draw, squarx] (B) [right=of X] {$v$};
  \node[draw, house] (H) [below=of X] {$h_{uv}$};
  \node[draw, circle] (D) [above=of X] {$\emptyset$};

  \draw[->] (A) edge node[above]{$d_{uv}(s, t)$}  (B);
  \draw[->] (A) edge node[above left]{$\zeta_u(s)$} (D);
  \draw[->] (A) edge node[below left]{$\eta_{uv}(s,t)$} (H);
  \draw[->] (H) edge node[below right]{$\rho_{uv}(s,t)$} (B);
\end{tikzpicture}
```

Sketch of the generalised model with processes of 1. permanent discharge ($u \to \emptyset$), 2. direct transfer ($u \to v$), 3. return home ($u \to h_{uv}$, 4. readmission $h_{uv} \to v$).
:::

Here, $u$ and $v$ are locations (potentially identical locations), $s$ and $t$ are times. We take that $t \geq s$.
$\emptyset$ represents patients that are not observed to return to the hospital system after their discharge from location $u$. We assume the associated hazard for this process ($\zeta_u(t)$) to be known for all locations $u$ at all times $t$: the modelling of this process is the same for all network models, and will be neglected in the following.

Further, we define the function $w_{uv}(s, t)$ to be the number of individuals that are observed to discahrge from $u$ at time $s$ and readmit at time $t$. We allow a maximum of one of the pairs $u,v$ and $s,t$ to be reflexive, i.e. $u=v$ or $s=t$, but not both.

We will also assume that we will have quantities $N_u$ that represent the "size" of a location $u$. We assume that all locations $u$ will have $N_u$ individuals in them at all times, and that the observed mvoements $w_{uv}(s, t)$ can be thought of as being scaled by $N_u$.

The governing equations can be roughly expressed as a function of the hazards of each process.

$$\begin{aligned}
\lambda(u(s) \to \emptyset) &= \zeta_u(s)\\
\lambda(u(s) \to v(t)) &= d_{uv}(s, t)\\
\lambda(u(s) \to z_{uv}(s, t)) &= \eta_{uv}(s, t)\\
\lambda(z_{uv}(s, t) \to v(t)) &= \rho_{uv}(s, t)
\end{aligned}$$

We note that as a consequence of the model structure, the hazards can also be interpreted as modelling the hodling time an individual patient spends in each state. 

### Naïve Static Model

We can begin with a simple naive static model. This model will have the edge weights between healthcare facilities that represent the number of transfers from the source node to the target node over a certain period of observation time ($T_\Sigma$), regardless of how long the patient is absent from the healthcare facilities between initial discharge and subsequent readmission.

With reference to the general model above, the hazards of the  naïve static model are:
$$d_{uv}(s,t) = d_{uv} = \frac{\sum_{s,t} w_{uv}(s,t)}{T_\Sigma N_u}$$
$$\eta_{uv}(s,t) = \eta_{uv} = 0$$
$$\rho_{uv}(s,t) = \rho_{uv} = 0$$

That is, all movements are instantaneous, and the rate of movement is the mean rate of movement over the entire observation period. This is an oversimplification of the work done in @donker, but represents a "worst" case model of temporal fidelity that can be benchmarked against.

### Improved Static Model

We can introduce the concept of "indirectness" by allowing individuals to return home, in an "improved" static model.
In this model, we choose some threshold value $\omega$ that delineates direct transfers that occur "instantaneously" and indirect transfers that require a patient to first move to an intermediary "home" state before readmitting.

In comparison to the naive model, we will have non-zero hazards $\eta$ and $\rho$:

$$d_{uv}(s,t) = d_{uv} =  \frac{\sum_{s,t: (t-s) < \omega} w_{uv}(s,t)}{T_\Sigma N_u}$$
$$\eta_{uv}(s,t) = \eta_{uv} = \frac{\sum_{s,t: (t-s) \geq \omega} w_{uv}(s,t)}{T_\Sigma N_u}$$
$$\rho_{uv}(s,t) = \rho_{uv} = \left[ \frac{\sum_{s,t: (t-s) \geq \omega} (t-s) w_{uv}(s,t)}{\sum_{s,t: (t-s) \geq \omega} w_{uv}(s,t)}  \right]^{-1}$$

Here, we model the rate of indirect transfers $\eta$ similarly to the rate of direct transfers  $d$, by counting the average rate of observed movements. For the rate of readmission, $\rho$, we use the inverse of the mean readmission duration/delay.

### Snapshot Model

Of course, as the hospital system changes over time, the rate of patient transfers, and thus the hazards represented in our model should also change.
We see evidence of this in the overall rates of movement in the network over time

.... need a plot here of total direct/direct over time

We approach this using static network snapshots of the hospital system over time. 

For the snapshot model, we choose a snapshot duration $\omega$. This defines the threshold duration of an indirect transfer.
This introduces an new intermediary state variable $z'$ that contains the individuals that would enter $z$ within the duration of a given snapshot $[t, t+\omega]$, so that they do not immediately readmit to their next hospital.
This alters the indirect transfer processes to

$$\begin{aligned}
\lambda(u(s) \to {z'}_{uv}(s)) &= \sum_t \eta_{uv}(s, t)\\
\lambda({z'}_{uv}(t) \to z_{uv}(t)) &= \delta(t \mod\omega)\\
\end{aligned}$$

where $\delta(\cdot)$ is the Dirac delta function.
Alongside this, we also compute from the data, the number of patients "at home" at a given time, in order to inform the denominator for the process from $z'$ to $z$. We denote this quantity $H_{uv}(t)$
We will have that:

$$d_{uv}(s,t) = d_{uv}(s) = \frac{\sum_{t: (t-s) < \omega} w_{uv}(s,t)}{\omega N_u}$$
$$\eta_{uv}(s,t) = \eta_{uv}(s) = \frac{\sum_{t: (t-s) \geq \omega} {w_{uv}(s, t)}}{\omega N_u}$$
$$\rho_{uv}(s,t) = \rho_{uv}(t) = \frac{\sum_{s: (t-s) \geq \omega} {w_{uv}(s, t)}}{\omega H_{uv}}$$

### Temporal Model

For the temporal network, we make a choice of the time discretisation $\omega$. That is, events that occur within a time window $[\tau, \tau+\omega)$ are collapsed and aggregated to occur at time $\tau$. Over the observation (and simulation) period, we will have a series of time window boundaries $\{\tau_0, \tau_1, \dots\}$. We denote the smallest value in that set larger than a given time $t$ to be $\ceil{t}_\omega$
For the readmission process, we assume that individuals that would readmit within a given time window $[\tau, \tau+\omega)$ do so uniformly. 
This yields:

$$d_{uv}(s, t) = \frac{\sum_{t: (t-s) < \omega} w_{uv}(s, t)}{\omega N_u}$$
$$\eta_{uv}(s, t) = \frac{\sum_{t: (t-s) \geq \omega} w_{uv}(s, t)}{\omega N_u}$$
$$\rho_{uv}(s,t) = \frac{1}{\ceil{t}_\omega - t}$$
